#!/usr/bin/env python3
"""
make_tables.py
==============
Rebuild the manuscript's data-dependent tables with the current runs.

  Table 2  Pooled AUC (95% CI) of GA/MI four-feature models, 10 BW x 3 scalers
           + DeLong stars (GA vs MI within scaler) and scaler daggers (vs PT)
  Table 3  Features at the MI-optimal config (StandardScaler, BW20)
  Table 4  Features at the GA-optimal config (RobustScaler, BW10)
  Table 5  Diagnostic performance at matched (RS BW10, SS BW20), threshold 0.5
  Table 6  Reference models vs GA/MI at matched scalers (SS BW20 / RS BW10 / PT BW10)
  Table S1 GA shape-triad stability (SS/RS, 10 BW)
  Table S2 GA BW10 top-4 selection frequency, RobustScaler vs PowerTransformer

GA runs: loo_r0.7_{S}_maxk4_noMI_inner1   MI runs: mi_loo_r0.7_{S}_inner1
Outputs: markdown + csv in this folder.
"""
from pathlib import Path

import numpy as np
import pandas as pd

import ga_mi_config as cfg

OUT = Path(__file__).resolve().parent
N_FOLDS = 80
SS_BW = cfg.GA_BW["StandardScaler"]   # 20  (MI-optimal StandardScaler bin width)
RS_BW = cfg.GA_BW["RobustScaler"]     # 10  (GA-optimal RobustScaler bin width)
PT_BW = cfg.GA_BW["PowerTransformer"] # 10  (matched to RobustScaler)


def ci(exp, bw):
    return cfg.bootstrap_all(exp)[bw]


def fmt_ci(ci_tuple):
    a, lo, hi = ci_tuple
    return f"{a:.3f} ({lo:.3f}, {hi:.3f})"


# ── Table 2 ─────────────────────────────────────────────────────────────────
def build_table2():
    cells = {}
    for s in cfg.SCALERS:
        ga = cfg.GA_NEW.format(s=s)
        mi = cfg.MI_NEW.format(s=s)
        for bw in cfg.BWS:
            _, p, a_ga, a_mi = cfg.delong_pair(ga, mi, bw)
            st = cfg.star_for_p(p)
            cells[(bw, f"GA {cfg.SHORT[s]}")] = (ci(ga, bw), st if st and a_ga > a_mi else "")
            cells[(bw, f"MI {cfg.SHORT[s]}")] = (ci(mi, bw), st if st and a_mi > a_ga else "")
    for tpl, meth in [(cfg.GA_NEW, "GA"), (cfg.MI_NEW, "MI")]:
        for s in ("StandardScaler", "RobustScaler"):
            m, pt = tpl.format(s=s), tpl.format(s="PowerTransformer")
            for bw in cfg.BWS:
                _, p, a_m, a_p = cfg.delong_pair(m, pt, bw)
                if a_m > a_p:
                    c, st = cells[(bw, f"{meth} {cfg.SHORT[s]}")]
                    cells[(bw, f"{meth} {cfg.SHORT[s]}")] = (c, st + cfg.dagger_for_p(p))
                elif a_p > a_m:
                    c, st = cells[(bw, f"{meth} PT")]
                    cells[(bw, f"{meth} PT")] = (c, st + cfg.dagger_for_p(p).replace("†", "‡"))
    return cells


def write_table2(cells):
    lines = ["# Table 2. Pooled AUC (95% CI) of the MI- and GA-selected four-feature models "
             "for all 10 bin widths and three scalers", "",
             "Current runs: GA = no-MI-init, 5 GA folds x 4 random seeds, 1 inner holdout; "
             "MI = 5 folds x 4 random seeds. SVM, k=4, 80 pooled LOO cases.",
             "",
             "| BW | StandardScaler GA | StandardScaler MI | RobustScaler GA | RobustScaler MI | "
             "PowerTransformer GA | PowerTransformer MI |",
             "|---:|---:|---:|---:|---:|---:|---:|"]
    for bw in cfg.BWS:
        row = [str(bw)]
        for s in cfg.SCALERS:
            for meth in ("GA", "MI"):
                ci_t, marks = cells[(bw, f"{meth} {cfg.SHORT[s]}")]
                row.append(fmt_ci(ci_t) + marks)
        lines.append("| " + " | ".join(row) + " |")
    lines += ["",
              "Stars mark the significantly better method within each scaler section "
              "(DeLong, two-sided): `*` p<0.05, `**` p<0.01, `***` p<0.001. "
              "Daggers mark an SS/RS cell significantly better than the same method under "
              "PowerTransformer (`†`/`††`/`†††`), or a PT cell significantly better than the same "
              "method under SS/RS (`‡`/`‡‡`/`‡‡‡`). CI = 1000-iteration percentile bootstrap.",
              "", f"*Generated by `{Path(__file__).name}`.*", ""]
    (OUT / "table2_pooled_auc.md").write_text("\n".join(lines), encoding="utf-8")
    rows = []
    for bw in cfg.BWS:
        r = {"bw": bw}
        for s in cfg.SCALERS:
            for meth in ("GA", "MI"):
                a, lo, hi = cells[(bw, f"{meth} {cfg.SHORT[s]}")][0]
                r[f"{meth}_{cfg.SHORT[s]}_auc"] = a
                r[f"{meth}_{cfg.SHORT[s]}_lo"] = lo
                r[f"{meth}_{cfg.SHORT[s]}_hi"] = hi
        rows.append(r)
    pd.DataFrame(rows).to_csv(OUT / "table2_pooled_auc.csv", index=False)
    print("Saved: table2_pooled_auc.md/.csv")


# ── Tables 3 & 4 (feature tables) ───────────────────────────────────────────
def feature_rows(ga_exp, mi_exp, bw):
    data = cfg.feature_group_stats(bw)
    out = []
    for method, exp in [("GA", ga_exp), ("MI", mi_exp)]:
        sel, _, _ = cfg.collect_feature_stats(exp, bw)
        for feat, cnt in sel.items():
            if feat not in data.columns:
                continue
            phase, ftype, fname = cfg.parse_feature_name(feat)
            g1, g0 = data.loc[data["Label"] == 1, feat], data.loc[data["Label"] == 0, feat]
            try:
                from scipy.stats import mannwhitneyu
                p = float(mannwhitneyu(g1, g0, alternative="two-sided").pvalue)
            except Exception:
                p = float("nan")
            out.append({"method": method, "phase": phase, "type": ftype, "feature": fname,
                        "fd_mean": float(g1.mean()), "fd_std": float(g1.std(ddof=1)),
                        "hcm_mean": float(g0.mean()), "hcm_std": float(g0.std(ddof=1)),
                        "p_value": p, "sel_count": cnt})
    df = pd.DataFrame(out)
    df["_ord"] = df["method"].map({"MI": 0, "GA": 1})
    df = df.sort_values(["_ord", "sel_count", "p_value"],
                        ascending=[True, False, True]).drop(columns="_ord")
    return df.reset_index(drop=True)


def write_feature_table(df, fname, title, note):
    lines = [f"# {title}", "", note, "",
             "| Method | Phase | Type | Feature | FD | HCM | P value | Sel. freq. |",
             "|---|---|---|---|---:|---|---:|---:|"]
    for _, r in df.iterrows():
        lines.append(
            f"| {r['method']} | {r['phase']} | {r['type']} | {r['feature']} | "
            f"{r['fd_mean']:.3f} ± {r['fd_std']:.3f} | "
            f"{r['hcm_mean']:.3f} ± {r['hcm_std']:.3f} | "
            f"{r['p_value']:.3f} | {int(r['sel_count'])}/{N_FOLDS} |")
    lines += ["", f"*Generated by `{Path(__file__).name}`.*", ""]
    (OUT / fname).write_text("\n".join(lines), encoding="utf-8")
    df.to_csv(OUT / fname.replace(".md", ".csv"), index=False)
    print(f"Saved: {fname} / .csv")


# ── Table 5 (diagnostic performance) ────────────────────────────────────────
def diagnostic(exp, bw):
    yt, ys = cfg.load_scores(exp, bw)
    pred = (ys >= 0.5).astype(int)
    tp = int(((pred == 1) & (yt == 1)).sum())
    tn = int(((pred == 0) & (yt == 0)).sum())
    fp = int(((pred == 1) & (yt == 0)).sum())
    fn = int(((pred == 0) & (yt == 1)).sum())
    return (ci(exp, bw), tp / (tp + fn), tn / (tn + fp), (tp + tn) / len(yt))


def write_table5():
    configs = [("GA (RS, BW10)", cfg.CONFIG_GA_RS10),
               ("MI (RS, BW10)", cfg.CONFIG_MI_RS10),
               ("GA (SS, BW20)", cfg.CONFIG_GA_SS20),
               ("MI (SS, BW20)", cfg.CONFIG_MI_SS20)]
    star = {}
    for (lg, eg), (lm, em) in [(configs[0], configs[1]), (configs[2], configs[3])]:
        _, p, a_g, a_m = cfg.delong_pair(eg[0], em[0], eg[1]) if eg[1] == em[1] else (np.nan,) * 4
        star[lg] = cfg.star_for_p(p) if a_g > a_m else ""
        star[lm] = cfg.star_for_p(p) if a_m > a_g else ""
        star[("p", lg, lm)] = p
    lines = ["# Table 5. Diagnostic performance of the GA- and MI-based models at the matched "
             f"(RobustScaler BW{RS_BW} and StandardScaler BW{SS_BW}) configurations", "",
             "Sensitivity / specificity / accuracy at the 0.5 decision threshold on pooled LOO "
             "SVM probabilities (n=80; 40 FD, 40 HCM). Current runs.", "",
             "| Config | AUC (95% CI) | Sensitivity | Specificity | Accuracy |",
             "|---|---|---:|---:|---:|"]
    rows = []
    for label, (exp, bw) in configs:
        (a, lo, hi), sens, spec, acc = diagnostic(exp, bw)
        lines.append(f"| {label} | {a:.3f} ({lo:.3f}–{hi:.3f}){star[label]} | "
                     f"{sens:.3f} | {spec:.3f} | {acc:.3f} |")
        rows.append({"config": label, "auc": a, "ci_lo": lo, "ci_hi": hi,
                     "sensitivity": sens, "specificity": spec, "accuracy": acc})
    p_rs = star.get(("p", "GA (RS, BW10)", "MI (RS, BW10)"), np.nan)
    p_ss = star.get(("p", "GA (SS, BW20)", "MI (SS, BW20)"), np.nan)
    lines += ["", "Stars: DeLong GA vs MI at the same configuration (two-sided, paired 80 cases).",
              f"DeLong p (GA vs MI, RS BW{RS_BW}) = {p_rs:.3f}; "
              f"DeLong p (GA vs MI, SS BW{SS_BW}) = {p_ss:.3f}.",
              "", f"*Generated by `{Path(__file__).name}`.*", ""]
    (OUT / "table5_diagnostic.md").write_text("\n".join(lines), encoding="utf-8")
    pd.DataFrame(rows).to_csv(OUT / "table5_diagnostic.csv", index=False)
    print("Saved: table5_diagnostic.md/.csv")


# ── Table 6 (reference models) ──────────────────────────────────────────────
def _fixed(model, scaler):
    bs = pd.read_csv(cfg.BASELINE_SUMMARY)
    r = bs[(bs.model == model) & (bs.scaler == scaler)].iloc[0]
    return float(r.auc_pooled), float(r.auc_lo), float(r.auc_hi)


def write_table6():
    cols = [("RobustScaler", RS_BW), ("StandardScaler", SS_BW), ("PowerTransformer", PT_BW)]
    rows = [("Fixed 3 features", [_fixed("fixed_triad3", s) for s, _ in cols]),
            ("Fixed 4 features", [_fixed("fixed_triad4", s) for s, _ in cols]),
            ("GA-selected (top 4)", [ci(cfg.GA_NEW.format(s=s), bw) for s, bw in cols]),
            ("MI-selected (top 4)", [ci(cfg.MI_NEW.format(s=s), bw) for s, bw in cols])]
    header = ["Model"] + [f"{s} (BW{bw})" for s, bw in cols]
    lines = ["# Table 6. Pooled AUC (95% CI) of the reference models and the GA- and "
             "MI-selected four-feature models at matched scalers", "",
             f"Columns at each method's representative config: RobustScaler BW{RS_BW} (GA peak), "
             f"StandardScaler BW{SS_BW} (MI peak), PowerTransformer BW{PT_BW}. "
             "Fixed models are bin-width invariant; values from the LOO baseline run. "
             "CI = 1000-iteration percentile bootstrap.", "",
             "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    csv_rows = []
    for label, cells in rows:
        lines.append(f"| {label} | " + " | ".join(fmt_ci(c) for c in cells) + " |")
        csv_rows.append({"model": label, **{f"{s}_BW{bw}": fmt_ci(cells[i]) for i, (s, bw) in enumerate(cols)}})
    (OUT / "table6_reference_models.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    pd.DataFrame(csv_rows).to_csv(OUT / "table6_reference_models.csv", index=False)
    print("Saved: table6_reference_models.md/.csv")

    # Companion DeLong: fixed4 / MWU vs GA / MI at the displayed configs
    fixed4 = pd.read_csv(cfg.BASELINE_FIXED)
    mwu = pd.read_csv(cfg.BASELINE_MWU)
    drows = []
    for s, bw in cols:
        base4 = fixed4[(fixed4.model == "fixed_triad4") & (fixed4.scaler == s)].sort_values("case_id")
        base3 = fixed4[(fixed4.model == "fixed_triad3") & (fixed4.scaler == s)].sort_values("case_id")
        basem = mwu[(mwu.scaler == s) & (mwu.bw == bw)].sort_values("case_id")
        for meth, tpl in [("GA", cfg.GA_NEW), ("MI", cfg.MI_NEW)]:
            yt, ys = cfg.load_scores(tpl.format(s=s), bw)
            for bname, bdf in [("fixed_triad3", base3), ("fixed_triad4", base4), ("mwu_top4", basem)]:
                z, p, a_b, a_r = cfg.delong_arrays(bdf.y_true.values, bdf.y_score.values, ys)
                drows.append({"scaler": s, "bw": bw, "baseline": bname, "reference": meth,
                              "auc_baseline": a_b, "auc_reference": a_r, "z": z, "p": p,
                              "baseline_better": bool(p < 0.05 and a_b > a_r),
                              "reference_better": bool(p < 0.05 and a_r > a_b)})
    dd = pd.DataFrame(drows)
    dd.to_csv(OUT / "table6_delong_companion.csv", index=False)
    dl = ["# Table 6 companion — DeLong reference-model contrasts (LOO, SVM, k=4)", "",
          "z signed as z = (AUC_reference − AUC_baseline)/SE. Baselines from `workspace/baselines/`; "
          "reference = current GA/MI runs.", "",
          "| scaler | BW | baseline | reference | AUC baseline | AUC reference | z | p | sig |",
          "|---|---:|---|---|---:|---:|---:|---:|---|"]
    for _, r in dd.iterrows():
        sig = ""
        if r["p"] < 0.05:
            sig = r["reference"] if r["reference_better"] else r["baseline"]
        dl.append(f"| {r['scaler']} | {int(r['bw'])} | {r['baseline']} | {r['reference']} | "
                  f"{r['auc_baseline']:.3f} | {r['auc_reference']:.3f} | {r['z']:.3f} | "
                  f"{r['p']:.4g} | {sig} |")
    (OUT / "table6_delong_companion.md").write_text("\n".join(dl) + "\n", encoding="utf-8")
    print("Saved: table6_delong_companion.md/.csv")


# ── S1 / S2 ─────────────────────────────────────────────────────────────────
def write_s1():
    rows = []
    for bw in cfg.BWS:
        r = {"bw": bw}
        for s in ("StandardScaler", "RobustScaler"):
            sel, _, _ = cfg.collect_feature_stats(cfg.GA_NEW.format(s=s), bw)
            r[f"{cfg.SHORT[s]}_Elongation"] = sel.get(cfg.ELONG, 0)
            r[f"{cfg.SHORT[s]}_Sphericity"] = sel.get(cfg.SPHER, 0)
            r[f"{cfg.SHORT[s]}_Flatness"] = sel.get(cfg.FLAT, 0)
        rows.append(r)
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "tableS1_ga_triad_stability.csv", index=False)
    lines = ["# Table S1. GA shape-triad stability (current run)", "",
             "Folds (of 80) in which each end-systolic shape descriptor entered the GA top 4, "
             "per bin width, under StandardScaler and RobustScaler.", "",
             "| BW | SS Elongation | SS Sphericity | SS Flatness | RS Elongation | RS Sphericity | RS Flatness |",
             "|---:|---:|---:|---:|---:|---:|---:|"]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(str(int(v)) for v in r) + " |")
    lines += ["", f"*Generated by `{Path(__file__).name}`.*", ""]
    (OUT / "tableS1_ga_triad_stability.md").write_text("\n".join(lines), encoding="utf-8")
    print("Saved: tableS1_ga_triad_stability.md/.csv")


def write_s2():
    counts = {}
    for s in ("RobustScaler", "PowerTransformer"):
        sel, _, _ = cfg.collect_feature_stats(cfg.GA_NEW.format(s=s), 10)
        counts[s] = sel
    feats = set(counts["RobustScaler"]) | set(counts["PowerTransformer"])
    priority = {f: i for i, f in enumerate([cfg.ELONG, cfg.SPHER, cfg.FLAT])}
    rows = [{"feature": cfg.short_name(f),
             "RobustScaler": counts["RobustScaler"].get(f, 0),
             "PowerTransformer": counts["PowerTransformer"].get(f, 0),
             "_mx": max(counts["RobustScaler"].get(f, 0), counts["PowerTransformer"].get(f, 0)),
             "_prio": priority.get(f, 99)} for f in feats]
    df = (pd.DataFrame(rows).sort_values(["_mx", "_prio", "feature"], ascending=[False, True, True])
          .head(8).drop(columns=["_mx", "_prio"]).reset_index(drop=True))
    df.to_csv(OUT / "tableS2_ga_bw10_rs_vs_pt.csv", index=False)
    lines = ["# Table S2. GA top-4 selection frequency at BW10 — RobustScaler vs PowerTransformer "
             "(current run)", "",
             "Folds (of 80) in which the feature entered the GA top 4.", "",
             "| feature | RobustScaler | PowerTransformer |", "|---|---:|---:|"]
    for _, r in df.iterrows():
        lines.append(f"| {r['feature']} | {int(r['RobustScaler'])} | {int(r['PowerTransformer'])} |")
    lines += ["", f"*Generated by `{Path(__file__).name}`.*", ""]
    (OUT / "tableS2_ga_bw10_rs_vs_pt.md").write_text("\n".join(lines), encoding="utf-8")
    print("Saved: tableS2_ga_bw10_rs_vs_pt.md/.csv")


def main():
    write_table2(build_table2())
    t3 = feature_rows(cfg.GA_NEW.format(s="StandardScaler"), cfg.MI_NEW.format(s="StandardScaler"), SS_BW)
    write_feature_table(t3, "table3_features_ss20.md",
                        f"Table 3. Features selected at the MI-optimal configuration (StandardScaler, bin width {SS_BW})",
                        "Features listed by descending selection frequency, MI block then GA block. "
                        "FD/HCM = mean ± SD of the untransformed feature over 40/40 cases; "
                        "p = Mann-Whitney U (two-sided); sel. freq. = LOO folds (of 80) ranking the feature top-4. "
                        "Current runs (GA no-MI-init 4-seed/1-inner; MI 4-seed).")
    t4 = feature_rows(cfg.GA_NEW.format(s="RobustScaler"), cfg.MI_NEW.format(s="RobustScaler"), RS_BW)
    write_feature_table(t4, "table4_features_rs10.md",
                        f"Table 4. Features selected at the GA-optimal configuration (RobustScaler, bin width {RS_BW})",
                        "Features listed by descending selection frequency, MI block then GA block. "
                        "FD/HCM = mean ± SD of the untransformed feature over 40/40 cases; "
                        "p = Mann-Whitney U (two-sided); sel. freq. = LOO folds (of 80) ranking the feature top-4. "
                        "Current runs (GA no-MI-init 4-seed/1-inner; MI 4-seed).")
    write_table5()
    write_table6()
    write_s1()
    write_s2()


if __name__ == "__main__":
    main()
