#!/usr/bin/env python3
"""
verify_old_vs_new.py
====================
Sanity check that the new 4-seed runs reproduce the previous (8-seed) runs.

  GA  old loo_r0.7_{S}_noMIinit  ->  new loo_r0.7_{S}_maxk4_noMI_inner1
  MI  old mi_loo_r0.7_{S}        ->  new mi_loo_r0.7_{S}_inner1

Outputs (this folder):
  verification_old_vs_new.md    per-BW pooled AUC + DeLong for GA and MI, all scalers,
                                plus full-ranking Spearman and top-4 Jaccard overlap.
  verification_summary.csv      machine-readable version of the AUC comparison.
"""
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

import ga_mi_config as cfg

OUT = Path(__file__).resolve().parent


def ranking_overlap(old_exp, new_exp, bw):
    so, ro, _ = cfg.collect_feature_stats(old_exp, bw)
    sn, rn, _ = cfg.collect_feature_stats(new_exp, bw)
    t_o, t_n = set(so), set(sn)
    jac = len(t_o & t_n) / len(t_o | t_n) if (t_o | t_n) else float("nan")
    so_s = pd.Series(ro).sort_values(ascending=False)
    sn_s = pd.Series(rn).sort_values(ascending=False)
    common = so_s.index.intersection(sn_s.index)
    rho = float(spearmanr(so_s.loc[common], sn_s.loc[common]).statistic) if len(common) >= 2 else float("nan")
    return rho, jac


def main():
    rows = []
    lines = ["# Verification — new (4-seed) vs previous (8-seed) runs", "",
             "New: GA `loo_r0.7_{S}_maxk4_noMI_inner1` (5 GA folds x 4 random seeds, 1 inner holdout); "
             "MI `mi_loo_r0.7_{S}_inner1` (5 folds x 4 random seeds).",
             "Old: GA `loo_r0.7_{S}_noMIinit` (5 GA folds x 8 random seeds, 3 inner folds); "
             "MI `mi_loo_r0.7_{S}` (5 folds x 8 random seeds).",
             "All values are pooled LOO AUC (SVM, k=4, 80 cases). DeLong is two-sided, paired.",
             ""]

    for method, old_tpl, new_tpl in [("GA", cfg.GA_OLD, cfg.GA_NEW),
                                     ("MI", cfg.MI_OLD, cfg.MI_NEW)]:
        lines += [f"## {method}", "",
                  "| Scaler | BW | old AUC | new AUC | ΔAUC (new−old) | DeLong p | Spearman ρ | top-4 Jaccard |",
                  "|---|---:|---:|---:|---:|---:|---:|---:|"]
        for s in cfg.SCALERS:
            old_exp, new_exp = old_tpl.format(s=s), new_tpl.format(s=s)
            for bw in cfg.BWS:
                z, p, a_old, a_new = cfg.delong_pair(old_exp, new_exp, bw)
                rho, jac = ranking_overlap(old_exp, new_exp, bw)
                rows.append({"method": method, "scaler": cfg.SHORT[s], "bw": bw,
                             "auc_old": a_old, "auc_new": a_new,
                             "delta_auc": a_new - a_old, "delong_p": p,
                             "spearman_rho": rho, "top4_jaccard": jac})
                lines.append(f"| {cfg.SHORT[s]} | {bw} | {a_old:.3f} | {a_new:.3f} | "
                             f"{a_new - a_old:+.3f} | {p:.4g} | {rho:.3f} | {jac:.3f} |")
        lines.append("")

    df = pd.DataFrame(rows)
    df.to_csv(OUT / "verification_summary.csv", index=False)

    lines += ["## Summary", ""]
    for method in ["GA", "MI"]:
        for s in cfg.SCALERS:
            sub = df[(df.method == method) & (df.scaler == cfg.SHORT[s])]
            n_sig = int((sub.delong_p < 0.05).sum())
            old_peak = sub.loc[sub.auc_old.idxmax()]
            new_peak = sub.loc[sub.auc_new.idxmax()]
            lines.append(
                f"- **{method} {cfg.SHORT[s]}**: mean ΔAUC {sub.delta_auc.mean():+.4f}; "
                f"DeLong p<0.05 in {n_sig}/10 BWs; ρ {sub.spearman_rho.min():.3f}–{sub.spearman_rho.max():.3f}; "
                f"peak BW {int(old_peak.bw)} ({old_peak.auc_old:.3f}) → {int(new_peak.bw)} ({new_peak.auc_new:.3f}).")
    lines += ["", f"*Generated by `{Path(__file__).name}`.*"]
    (OUT / "verification_old_vs_new.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
